platform :osx, "10.7"

pod 'Reachability'

target :TakeOffTests, :exclusive => false do
	pod 'OCMock', '~> 2.2.1'
end

post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_ENABLE_OBJC_GC'] = 'supported'
    end
  end
end
